### ISSUE TITLE
[Crash Report] Possible AttributeInstance problem

### ISSUE THREAD

**Issue by Desempregago** [Foghrye4/Iblis#2]
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111122_c(SourceFile:62)
	at net.minecraft.network.play.server.SPacketEntityProperties.<init>(SourceFile:26)
	at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:327)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:273)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:292)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

Using latest Iblis (0.3.8) and Minecraft Forge 2491 (1.12.2)
I've disabled the Jumping ability, but I think the mod is still "listening" to the jumping attribute, hence the AtributeInstance error

**Comment by Foghrye4** [comment]
There is a two possible sources of a bug:
1. Sprinting speed modifier was applied client-side.
2. Mining skill could be raised client-side.
Both of them are fixed (0.3.9). If bug occurs again, report on what are you did in a moment of it: jumping, sprinting, shooting, digging or anything else. Or it occur in a moment of joining a world?
