### ISSUE TITLE
[Crash Report] Crafting/Smithing ability being applied client-side

### ISSUE THREAD

**Issue by Desempregago** [Foghrye4/Iblis#3]
java.lang.IllegalStateException: Skills should be raised only at server side.
	at iblis.player.PlayerSkills.raiseSkill(PlayerSkills.java:32)
	at iblis.crafting.PlayerSensitiveRecipeWrapper.raiseSkill(PlayerSensitiveRecipeWrapper.java:96)
	at iblis.crafting.CraftingHandler.onAnvilRepair(CraftingHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_857_CraftingHandler_onAnvilRepair_AnvilRepairEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onAnvilRepair(ForgeHooks.java:935)
	at net.minecraft.inventory.ContainerRepair$2.func_190901_a(ContainerRepair.java:73)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiRepair.func_73864_a(SourceFile:125)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

Latest Iblis (0.3.16) and Forge (2512)

**Comment by Foghrye4** [comment]
Fixed, thank you.
